### ISSUE TITLE
如果录播姬去除 session 相关的概念和 webhook 是否会对本项目产生较大影响？

### ISSUE THREAD

**Issue by Genteure** [Frefreak/misc#4]
最近在研究重构录播姬，添加 HLS 录制支持，重构其中一项是打算去除现在录播姬的 session 这个概念以及对应的 webhook 事件。
我通过 GitHub 全局代码搜索关键词找到本项目，简单看了一下使用了 `SessionEnded` 来触发上传文件，是这样的吧？
如果录播姬去除了相关概念和webhook事件是否会对你的工作流产生较大影响？

**Comment by Frefreak** [comment]
影响不大，到时可以相应地调整
